#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum class ErrorCode {
    SUCCESS = 0,
    FOLDER_NOT_FOUND,
    WRONG_FOLDER_SPECIFIED,
    INTERVAL_NOT_SPECIFIED,
    WRONG_INTERVAL_FORMAT,
    NEGATIVE_INTERVAL,
    LOG_FILE_WRITE_ERROR,
    LOG_FILE_FORMAT_ERROR,
    WRONG_NUMBER_OF_ARGUMENTS
};

#endif // ERROR_CODES_H